# Change these first
owner: subscribili # Your GitHub organization or username, where this repository lives
repo: subscribili-status # The name of this repository

sites:
  - name: Subscribili
    url: https://app.subscribili.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.subscribili.com
  # baseUrl: /your-repo-name
  favicon: /favicon.ico
  logoUrl: /logo.svg
  name: Subscribili
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
